Fix build with latest qtbase
Fix errors like

  qtbase/src/corelib/kernel/qobject_p.h(497): error C2248: 'QOAuth2AuthorizationCodeFlowPrivate::q_func': cannot access private member declared in class 'QOAuth2AuthorizationCodeFlowPrivate'

caused by commit 0e72a846d379 in qtbase.

Change-Id: Iaf99abe5369c3242f514450d25dd1cd5af675df6
Reviewed-by: Marc Mutz <marc.mutz@qt.io>
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>